curl -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWJiZGY0ODExNzI2NzQwYjhhNTFmZjgiLCJpYXQiOjE3MDY4MTEyNTAsImV4cCI6MTcwOTQwMzI1MH0.OXyUjSzFyPtz9KpMkDegrO5k4NiiMHTxouaSFDKUY-4' localhost:8080/products -v

